# shellcheck disable=SC2154,SC2329,SC2034,SC2317
# prelude-ble.sh — Prelude × ble.sh integration.
#
# Sourced by the prelude-shell-vt-status-spike host after Starship/ble.sh setup.
# This is the ble.sh-facing counterpart of the Go host's chrome: ble.sh owns
# completion descriptions, ghost text, sabbrev snippets, and syntax validation;
# the Go host owns VT composition, scrollback, and the shared 2-row chrome.
#
# Requires ble.sh (bash). The companion prelude-catalog.sh (generated by the
# Go host into the same directory) must be sourced first so that the
# prelude_catalog_* arrays and prelude_palette_* indices are defined.
#
# Disabled checks (all indirect): SC2154 — vars assigned by the sourced
# catalog; SC2329/SC2034 — init-menu-item and g are consumed by ble.sh's menu
# engine (modelled on Recipes R3); SC2317 — the exit guard covers direct
# execution rather than a source.
#
# Only act under ble.sh. The standalone-Starship fallback path never loads it.
if [[ -z ${BLE_VERSION:-} ]]; then
  return 0 2>/dev/null || exit 0
fi

# -- Catalog lookups -----------------------------------------------------------

prelude/catalog/find-by-name() {
  local needle=$1 i
  for i in "${!prelude_catalog_names[@]}"; do
    if [[ ${prelude_catalog_names[i]} == "$needle" ]]; then
      REPLY=$i
      return 0
    fi
  done
  return 1
}

prelude/catalog/find-by-command() {
  local needle=$1 i
  for i in "${!prelude_catalog_commands[@]}"; do
    if [[ ${prelude_catalog_commands[i]} == "$needle" ]]; then
      REPLY=$i
      return 0
    fi
  done
  return 1
}

# -- A single candidate action whose DATA is the description shown in desc menu --

# Modelled on ble.sh wiki "Recipes" R3: define a face, inherit from word, and set
# the menu-item graphics in init-menu-item so complete_menu_style=desc renders
# the third argument to ble/complete/cand/yield as the candidate description.
prelude/ble/define-cand-action() {
  ble/color/defface prelude_cand_description "fg=${prelude_palette_muted}"
  ble/complete/action#inherit-from prelude_cand word
  function ble/complete/action:prelude_cand/init-menu-item {
    local ret
    ble/color/face2g prelude_cand_description
    g=$ret
  }
}

# -- Palette → ble.sh faces ----------------------------------------------------

prelude/ble/apply-palette() {
  ble-face auto_complete="fg=${prelude_palette_dim}"
  ble-face menu_desc_default="fg=${prelude_palette_muted}"
  ble-face menu_desc_type="fg=${prelude_palette_dim}"
  ble-face menu_desc_quote="fg=${prelude_palette_accent2}"
  ble-face menu_complete_match="fg=${prelude_palette_accent}"
  ble-face menu_complete_selected="reverse"
  ble-face menu_filter_fixed="fg=${prelude_palette_muted}"
  ble-face menu_filter_input="fg=${prelude_palette_info}"
}

# -- Progcomp functions --------------------------------------------------------

# `x <task> [<args…>]` — Tab on `x ` lists project tasks with descriptions.
prelude/complete/x() {
  local prefix=${COMP_WORDS[COMP_CWORD]}
  if (( COMP_CWORD <= 1 )); then
    bleopt complete_menu_style=desc
    compopt -o nosort 2>/dev/null || true
    local i name desc
    for i in "${!prelude_catalog_names[@]}"; do
      name=${prelude_catalog_names[i]}
      [[ $name == "$prefix"* ]] || continue
      desc=${prelude_catalog_descriptions[i]:-$name}
      ble/complete/cand/yield prelude_cand "$name" "$desc"
    done
    return
  fi
  # x <task> <args…> — offer the task's declared option candidates.
  local idx
  prelude/catalog/find-by-name "${COMP_WORDS[1]}" || return 0
  local opts=${prelude_catalog_argopts[idx]}
  [[ -n $opts ]] || return 0
  local opt
  for opt in $opts; do
    [[ $opt == "$prefix"* ]] || continue
    ble/complete/cand/yield word "$opt" ""
  done
}

# `<direct command> [<args…>]` — offer the command's declared option candidates.
prelude/complete/direct() {
  local prefix=${COMP_WORDS[COMP_CWORD]}
  local idx
  prelude/catalog/find-by-command "${COMP_WORDS[0]}" || return 0
  local opts=${prelude_catalog_argopts[idx]}
  [[ -n $opts ]] || return 0
  local opt
  for opt in $opts; do
    [[ $opt == "$prefix"* ]] || continue
    ble/complete/cand/yield word "$opt" ""
  done
}

# -- One-time setup, deferred until ble.sh's completion module is loaded ---------

prelude/ble/setup() {
  prelude/ble/apply-palette
  prelude/ble/define-cand-action

  complete -F prelude/complete/x x
  local cmd
  for cmd in "${prelude_direct_commands[@]}"; do
    complete -F prelude/complete/direct "$cmd"
  done

  # Menu behaviour: descriptions on candidates, filter-as-you-type, auto ghost
  # text, and an auto-menu after a short idle. info_display=top keeps the menu
  # below the prompt and away from the host's bottom chrome.
  bleopt complete_menu_filter=1
  bleopt complete_auto_complete=1
  bleopt complete_auto_delay=1
  bleopt complete_auto_menu=300
  bleopt info_display=top

  # Expand trailing sabbrev on Enter and refuse to execute malformed lines.
  bleopt edit_magic_accept=sabbrev:verify-syntax

  # Project-aware snippets. Dynamic sabbrev (-m) runs a shell function that fills
  # COMPREPLY; the static form substitutes the right-hand side directly.
  ble-sabbrev '\date'='date +%F'
  ble-sabbrev '\pwd'='pwd'
}
blehook/eval-after-load complete prelude/ble/setup
