# This repo's own devshell UI, built by its own module (see flake.nix):
# `nix develop` greets with our motd and `menu` drives the project.
{
  theme = "apathy";
  # Hook contexts (direnv, wrapped shells) sometimes capture stderr, which
  # is where gum sniffs the terminal — degrading truecolor to 256. Force
  # 24-bit so the shellHook motd matches an interactive `motd`.
  colorProfile = "truecolor";
  project = "prelude";

  groups = {
    general = {
      order = 100;
      tasks = {
        motd = {
          order = 100;
          description = "reprint the welcome banner";
        };
        menu = {
          description = "open this command menu";
        };
      };
    };
    develop = {
      tasks = {
        check = {
          run = "nix flake check";
          description = "build + render smoke tests";
          key = "c";
        };
        fmt = {
          run = "nix fmt";
          description = "format nix sources";
          key = "f";
        };
        previews = {
          run = "nix run .#previews";
          description = "build the render checks and show their output";
          key = "p";
        };
        build = {
          run = "nix build";
          description = "build a flake output";
          key = "b";
          usage = "menu build .#motd";
          args = [
            {
              token = "<target>";
              description = "flake output to build";
              options = [
                ".#motd"
                ".#menu"
                ".#example-themes"
              ];
            }
          ];
        };
      };
    };
    demos = {
      tasks = {
        examples = {
          run = "nix run .#examples";
          description = "tour every feature demo";
          key = "e";
        };
        themes = {
          run = "nix run .#example-themes";
          description = "render a mini motd per theme";
          key = "t";
        };
        demo-motd = {
          run = "nix run .#example-motd";
          description = "acme-web welcome banner demo";
        };
        demo-menu = {
          run = "nix run .#example-menu";
          description = "acme-web command menu demo (arg entry)";
        };
      };
    };
  };

  motd = {
    enable = true;
    banner.tagline = "devshell UI, generated by Nix — motd · menu";
    banner.statusItems = [
      {
        text = "devshell";
        status = "success";
      }
    ];
    description.text = "Generated by our own flake-parts module — dogfooding the suite.";
    env = [
      {
        label = "nix";
        # awk NF: robust against "nix (Nix) 2.x" and "nix (Determinate Nix 3.x) 2.x"
        probe = "nix --version | awk '{print $NF}'";
      }
      {
        label = "gum";
        probe = "gum --version | awk '{print $NF}'";
      }
    ];
    commands = {
      browse = {
        command = "menu";
        description = "explore everything available";
      };
      check = {
        command = "nix flake check";
        description = "verify the flake";
      };
      previews = {
        command = "nix run .#previews";
        description = "inspect rendered examples";
      };
    };
    clearScreen = true;
    margin.bottom = 10;
  };

  menu.enable = true;
}
