package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// Config mirrors the JSON payload generated by src/prelude/menu.nix.
type Config struct {
	Project      string  `json:"project"`
	Placeholder  string  `json:"placeholder"`
	Height       int     `json:"height"`
	MaxWidth     int     `json:"maxWidth"` // 0 = unbounded
	Execute      bool    `json:"execute"`
	ColorProfile string  `json:"colorProfile"`
	Palette      Palette `json:"palette"`
	Groups       []Group `json:"groups"`
}

type Palette struct {
	Fg           string `json:"fg"`
	Muted        string `json:"muted"`
	Dim          string `json:"dim"`
	Border       string `json:"border"`
	AccentBorder string `json:"accentBorder"`
	Accent       string `json:"accent"`
	Accent2      string `json:"accent2"`
	Error        string `json:"error"`
	SelectionFg  string `json:"selectionFg"`
	Bg           string `json:"bg"`
	Surface      string `json:"surface"`
	Secondary    string `json:"secondary"`
}

type Group struct {
	Title string `json:"title"`
	Tasks []Task `json:"tasks"`
}

type Task struct {
	Name        string   `json:"name"`
	Run         string   `json:"run"`
	Description string   `json:"description"`
	Key         string   `json:"key"`   // "" = none
	Usage       string   `json:"usage"` // "" = none
	Details     string   `json:"details"`
	Examples    []string `json:"examples"`
	Args        []Arg    `json:"args"`

	group    string // owning group title
	haystack string // precomputed lowercase filter target
}

type Arg struct {
	Token       string   `json:"token"`
	Description string   `json:"description"`
	Required    bool     `json:"required"`
	Boolean     bool     `json:"boolean"`
	Options     []string `json:"options"`
}

func loadConfig(path string) (*Config, error) {
	if path == "" {
		return nil, fmt.Errorf("no config: pass --config or set PRELUDE_MENU_CONFIG")
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg Config
	if err := json.Unmarshal(raw, &cfg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	if cfg.Height <= 0 {
		cfg.Height = 12
	}
	return &cfg, nil
}

// flatten returns every task in group order with search metadata attached.
func (c *Config) flatten() []Task {
	var flat []Task
	for _, g := range c.Groups {
		for _, t := range g.Tasks {
			t.group = g.Title
			t.haystack = strings.ToLower(
				t.Name + " " + t.Usage + " " + t.Description + " " + t.group,
			)
			flat = append(flat, t)
		}
	}
	return flat
}

// find resolves a task by name or single-key accelerator.
func (c *Config) find(sel string) *Task {
	flat := c.flatten()
	for i := range flat {
		if flat[i].Name == sel {
			return &flat[i]
		}
	}
	for i := range flat {
		if flat[i].Key != "" && flat[i].Key == sel {
			return &flat[i]
		}
	}
	return nil
}

// tokenFor builds the token(s) an option inserts for an arg, mirroring the
// design demo's tokenFor().
func tokenFor(a Arg, option string) string {
	if a.Boolean {
		return a.Token
	}
	if strings.HasPrefix(a.Token, "--") {
		return a.Token + " " + option
	}
	return option // positional
}
