package title

import (
	"encoding/json"
	"fmt"
	"os"
)

// Font is one bundled FIGlet style available in the chooser.
type Font struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

// Theme is one bundled palette advertised to the setup wizard. The palette
// keys mirror the Nix theme tokens (accent, accent2, bg, …).
type Theme struct {
	Name    string            `json:"name"`
	Palette map[string]string `json:"palette"`
}

// Config is generated by Nix so the Go command does not need to discover font
// files at runtime. Themes are only consumed by the wizard; the plain chooser
// tolerates configs that omit them.
type Config struct {
	DefaultFont  string  `json:"defaultFont"`
	Fonts        []Font  `json:"fonts"`
	DefaultTheme string  `json:"defaultTheme"`
	Themes       []Theme `json:"themes"`
}

func loadConfig(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Config{}, fmt.Errorf("read config: %w", err)
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return Config{}, fmt.Errorf("decode config: %w", err)
	}
	if len(cfg.Fonts) == 0 {
		return Config{}, fmt.Errorf("config contains no fonts")
	}
	for _, font := range cfg.Fonts {
		if font.Name == "" || font.Path == "" {
			return Config{}, fmt.Errorf("config contains an invalid font entry")
		}
	}
	if cfg.fontIndex(cfg.DefaultFont) < 0 {
		cfg.DefaultFont = cfg.Fonts[0].Name
	}
	return cfg, nil
}

func (c Config) fontIndex(name string) int {
	for i, font := range c.Fonts {
		if font.Name == name {
			return i
		}
	}
	return -1
}

func (c Config) themeIndex(name string) int {
	for i, theme := range c.Themes {
		if theme.Name == name {
			return i
		}
	}
	return -1
}
