package title

import (
	"encoding/json"
	"fmt"
	"regexp"
)

// WizardConfig is the stable JSON record produced by the setup wizard.
// Nix owns option names, defaults, and command identity; Go only collects
// the user's choices and writes them as JSON plus a thin Nix reader.
type WizardConfig struct {
	Recipe       WizardRecipe    `json:"recipe"`
	Project      string          `json:"project"`
	Theme        string          `json:"theme"`
	ColorProfile string          `json:"colorProfile"`
	Motd         bool            `json:"motd"`
	Menu         bool            `json:"menu"`
	Prompt       bool            `json:"prompt"`
	Docs         bool            `json:"docs"`
	Commands     []WizardCommand `json:"commands"`
}

// WizardRecipe is the rendered title recipe referenced by the emitted config.
type WizardRecipe struct {
	Text string `json:"text"`
	Font string `json:"font"`
}

// WizardCommand is one user-collected command. Nix infers exec, group, usage,
// and invocation from the name when these fields are empty.
type WizardCommand struct {
	Name        string `json:"name"`
	Exec        string `json:"exec"`
	Description string `json:"description"`
}

// renderWizardJSON returns the wizard choices as compact JSON.
func renderWizardJSON(r wizardResult) string {
	cfg := WizardConfig{
		Recipe: WizardRecipe{
			Text: r.Recipe.Text,
			Font: r.Recipe.Font,
		},
		Project:      r.Project,
		Theme:        r.Theme,
		ColorProfile: r.ColorProfile,
		Motd:         r.Motd,
		Menu:         r.Menu,
		Prompt:       r.Prompt,
		Docs:         r.Docs,
		Commands:     make([]WizardCommand, len(r.Commands)),
	}
	for i, c := range r.Commands {
		cfg.Commands[i] = WizardCommand{
			Name:        c.Name,
			Exec:        c.Exec,
			Description: c.Description,
		}
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		panic(fmt.Sprintf("marshal wizard config: %v", err))
	}
	return string(data)
}

// renderWizardNix returns a minimal flake-parts module that reads the sibling
// prelude.json and maps it to prelude.* options. Keeping the mapping in a
// stable Nix expression means Go does not need to know the full option surface.
func renderWizardNix(jsonName string) string {
	return fmt.Sprintf(`# Generated by prelude setup.
#
# The real configuration lives in %s (produced alongside this file).
# This module reads that JSON and maps it to prelude.* options, so the
# wizard does not need to duplicate Nix option names or defaults.
{ lib, ... }:
let
  wizard = builtins.fromJSON (builtins.readFile ./%s);
in
{
  prelude = {
    inherit (wizard) theme colorProfile project;

    commands = lib.listToAttrs (
      map (
        c:
        lib.nameValuePair c.name {
          inherit (c) exec description;
        }
      ) wizard.commands
    );

    motd = {
      enable = wizard.motd;
      title.text = ./title.txt;
      # Footer link back to Prelude; replace with your own repository.
      header.statusHint.links = [
        {
          label = "github";
          url = "https://github.com/darkmatter/prelude";
        }
      ];
    };

    menu.enable = wizard.menu;
    prompt.enable = wizard.prompt;
    docs.pages = lib.optional wizard.docs { text = ./docs/getting-started.md; };
  };
}
`, jsonName, jsonName)
}

// commandKeyPattern accepts public keys such as `test:unit` and
// `test:unit:watch`. The first colon derives menu grouping; the complete key
// remains callable through `x`.
var commandKeyPattern = regexp.MustCompile(`^[A-Za-z0-9_.-]+(:[A-Za-z0-9_.-]+)*$`)

// nixPathLiteralPattern matches the characters Nix accepts in an unquoted
// path literal. Anything else (spaces most commonly) would emit a config
// that fails to parse, so output paths are validated up front.
var nixPathLiteralPattern = regexp.MustCompile(`^[A-Za-z0-9._+/-]+$`)

// starterDocsPath is both written by setup and referenced by the emitted
// config, so the generated module builds without manual steps.
const starterDocsPath = "docs/getting-started.md"

const starterDocsPage = `# Getting started

This page was created by ` + "`prelude setup`" + `.

Every Markdown file listed under ` + "`prelude.docs.pages`" + ` becomes one page in
the ` + "`docs`" + ` viewer; the first heading is the sidebar label. Replace this
page with real onboarding notes and add more pages as the project grows.
`
