# Generated by prelude-title --wizard.
#
# A flake-parts module: import it next to Prelude's module, e.g.
#
#   imports = [ prelude.flakeModules.default ./prelude.nix ];
#
{ ... }:
{
  prelude = {
    theme = "prelude";
    colorProfile = "auto";
    project = "prelude";

    motd = {
      enable = true;
      title = {
        text = ./title.txt;
        align = "center";
      };
    };
    menu.enable = true;
    prompt.enable = true;

    # Starter page written by the wizard; add more entries as docs grow.
    docs.pages = [{ text = ./docs/getting-started.md; }];
  };
}
