# Starter flake generated by `nix flake init -t github:darkmatter/prelude#default`.
#
# Imports Prelude's flake-parts module and configures a minimal MOTD, command
# menu, and docs viewer. Run `nix develop` to enter the shell — the MOTD
# prints automatically; `menu` opens the interactive picker and `docs`
# browses the Markdown pages under ./docs.
#
# Add project commands under prelude.commands (keyed by public `x` name;
# the first colon infers the menu group) and docs pages under prelude.docs.pages.
{
  description = "My Prelude-powered devshell";

  inputs = {
    prelude.url = "github:darkmatter/prelude";
    nixpkgs.follows = "prelude/nixpkgs";
    flake-parts.follows = "prelude/flake-parts";
  };

  outputs =
    inputs@{ flake-parts
    , prelude
    , ...
    }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      # 1. Import the Prelude flake-parts module.
      imports = [ prelude.flakeModules.default ];

      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      # 2. Configure Prelude.
      prelude = {
        theme = "phosphor";
        project = "my-project";

        motd.enable = true;
        menu.enable = true;

        # Project commands keyed by public `x` name. The first colon infers
        # the menu group; the full key stays callable (e.g. `x build:fast`).
        # commands.dev = {
        #   exec = "echo hello from the dev server";
        #   description = "start the dev server";
        # };

        docs.pages = [
          { text = ./docs/getting-started.md; }
        ];
      };

      perSystem =
        { config, pkgs, ... }:
        {
          devShells.default = pkgs.mkShell {
            packages = [ config.packages.prelude ];
            shellHook = "motd";
          };
        };
    };
}
