# Shared defaults for the prelude components (motd, menu).
#
# Single source of truth consumed by both the module options
# (src/prelude/options/*.nix) and the generators (fallbacks for direct
# mkMotd/mkMenu consumers).
#
# Text items intentionally carry no colors here — when `foreground` is null
# the generators fall back to the palette role for that element, so the
# selected theme drives the look. Explicit colors always win.
{
  # Theme name (see themes.nix) + per-token palette overrides.
  theme = "phosphor";
  palette = { };

  # Color depth: "auto" detects the terminal profile, "truecolor" forces
  # 24-bit output, and "ansi256" forces quantization to 256 colors.
  colorProfile = "auto";

  # Project identity, shared by motd and menu.
  project = "devshell";

  # Project commands keyed by invocation name for the interactive menu. The
  # flake-parts module contributes menu/docs when those components exist.
  # Commands sort by `order ? 1000`, then name; groups follow the first command.
  # Command: { exec ? commandKey, group ? "general", order ? 1000,
  #            description ? "", key ? null, usage ? null, details ? null,
  #            examples ? [ ], args ? [ { token, description ? "",
  #            required ? false, boolean ? false, options ? [ ] } ] }
  commands = { };

  # Inferred presentation-group order. The first colon in a command key names
  # its group; ungrouped commands fall under develop. Prelude navigation stays
  # first; unlisted groups follow alphabetically.
  sort.groups = [ "develop" ];

  # --- motd --------------------------------------------------------------------
  # Layout matches dev/playground/motd-playground: header bar → description → env →
  # Getting Started (commands + examples) → shortcuts.

  motd = {
    # The optional checked-in multiline text is generated by `prelude-title`;
    # null keeps the styled project-name wordmark. Alignment applies to custom
    # text, while style selects the fallback wordmark treatment.
    title = {
      text = null;
      align = "left";
      style = "spine";
    };

    # Block background fill: null/false = transparent, true = theme `bg`
    # token, or an explicit color. Falls back to windowBackground when
    # unset.
    background = null;

    # Window background: paints the full terminal width — margins,
    # alignment gutters, and line remainders. null/false = transparent,
    # true = theme `bg` token, or an explicit color.
    windowBackground = null;

    # Clear the terminal before rendering — with the top margin below this
    # renders as a clean greeting screen on shell entry.
    clearScreen = true;

    # Margin around the block: top/bottom blank lines, left/right columns
    # folded into the horizontal offset. x/y axes work as shorthands;
    # explicit sides supersede them.
    margin = {
      x = 0;
      y = 0;
      top = 10;
      bottom = null;
      left = null;
      right = null;
      # Vertical sides apply only at or above this terminal height (rows);
      # 0 always applies. Horizontal sides are unaffected.
      minHeight = 0;
    };

    # Horizontal placement of the motd block against the terminal window
    # (content inside stays left-aligned).
    align = "center";

    # Inner padding between content and the block edge. Header bar stays
    # edge-to-edge horizontally; tagline, middle, and footer shortcuts take
    # horizontal inset. Top and bottom pad the whole card outside the title
    # and shortcut rows.
    padding = {
      x = 0;
      y = 0;
      top = null;
      bottom = null;
      left = null;
      right = null;
      minHeight = 0;
    };

    # Hero bar: wordmark, status, and activation copy.
    header = {
      tagline = {
        text = "Dev Shell Activated";
        subtitle = "Your environment is ready";
        # stack = two lines; inline = "text · subtitle" on one row.
        layout = "stack";
        # left | center
        align = "left";
      };
      # true = raised lightened bar (default); null/false = transparent;
      # color / { relative } = explicit fill.
      background = true;
      statusHint = {
        # below = separate row; inline = lights left, hint right.
        layout = "below";
        # Hyperlinks appended after the reload hint. Item: { label; url; }
        links = [ ];
      };
      # Keyed lights: static { status } or live { check, ok?, fail? }.
      status = {
        ready = {
          status = "ready";
        };
      };
    };

    # Styled text rendered beneath the header (theme fg role). An empty
    # text hides it. { text, foreground, background, bold, italic, faint }
    description = {
      text = "";
    };

    # Terminal hyperlinks rendered beneath the description.
    # Item: { label; url; }
    links = [ ];

    # Env info chips, rendered in order. Each item sets exactly one of:
    #   { label; value; }  — static chip
    #   { label; probe; }  — command run at render time; first output line
    #                        becomes the value, skipped on failure
    env = [ ];

    # Multi-step workflows keyed by name. Prefer `steps`; legacy `lines`
    # are normalized into steps at the Nix boundary.
    recipes = { };

    # Unified commands + examples region labels.
    gettingStarted = {
      heading = "Getting Started";
      commandsLabel = "commands";
      examplesLabel = "examples";
    };

    width = "full";
    maxWidth = 96;
  };

  # --- menu --------------------------------------------------------------------

  menu = {
    # Placeholder in the filter input.
    placeholder = "type to filter commands…";

    # Filter list height (rows).
    height = 12;

    # Execute the selected command (exec bash -c). When false, print it instead.
    execute = true;

    width = "full";
    maxWidth = 96;
  };

  # --- prompt ------------------------------------------------------------------
  # Themed starship config (packages.prompt = starship.toml). Colors come from
  # the palette (path: muted, marker: accent2 — the documented prompt role —
  # continuation: dim). `settings` merges over the themed defaults;
  # `configFile` replaces the generated config entirely.

  prompt = {
    settings = { };
    configFile = null;
  };

  # --- docs --------------------------------------------------------------------
  # Markdown pages are empty by default. Each configured file becomes one page
  # in the navigable docs viewer.

  docs = {
    pages = [ ];
    rootReadme = null;
    nixosOptions = {
      options = { };
    };
  };
}
