# Build the canonical interactive-shell initialization used by packages.prelude.
#
# Runtime behavior lives in checked-in Bash modules under ./shell. Nix only
# serializes the evaluated command catalogue and injects immutable dependency
# paths, so changing shell behavior does not mean editing a large Nix string.
{
  lib,
  writeText,
  runCommand,
  starship,
  blesh,
  bash-completion,
  stdenv,
}:

{
  palette,
  shadow ? null,
  windowBackgroundSet ? false,
  commandEntries ? [ ],
  projectName ? "your project",
  navigation ? [ ],
  motdCommand ? null,
  statusEnabled ? false,
  promptStatusCommand ? null,
  promptStatusConfig ? null,
}:

let
  plib = import ./lib.nix { inherit lib; };
  resolvedShadow = if shadow == null then plib.lightenColor palette.bg else shadow;
  # Prompt markup is zero-width after ble.sh parses it, while status-row layout
  # runs before parsing. Keep a literal twin so padding always uses cell widths.
  # The status row is standalone; each `\g` span resets SGR, so spans without a
  # background render transparent over the prompt_status_line face.
  navigationText = lib.concatStringsSep "  " (
    map (shortcut: "[${shortcut.alias}] ${shortcut.command}") navigation
  );
  navigationRendered = lib.concatStringsSep "  " (
    map (
      shortcut:
      lib.concatStrings [
        "\\g{fg=${palette.dim}}["
        "\\g{bold,fg=${palette.accent2}}${shortcut.alias}"
        "\\g{fg=${palette.dim}}]"
        "\\g{fg=${palette.muted}} ${shortcut.command}"
      ]
    ) navigation
  );
  # Keep a visible-text twin: status.bash calculates padding before ble.sh
  # strips the trusted `\g` markup.
  hintText = "Run commands: x <cmd> or x ⇥";
  # Gradient stops from bg to shadow across the hint segments.
  gs0 = plib.mixColor palette.bg resolvedShadow 0.0;
  gs1 = plib.mixColor palette.bg resolvedShadow 0.33;
  gs2 = plib.mixColor palette.bg resolvedShadow 0.67;
  gs3 = plib.mixColor palette.bg resolvedShadow 1.0;
  hintRendered = lib.concatStrings [
    "\\g{fg=${palette.dim},bg=${gs0}}Run commands: "
    "\\g{bold,fg=${palette.dim},bg=${gs1}}x <cmd> "
    "\\g{fg=${palette.dim},bg=${gs2}}or "
    "\\g{bold,fg=${palette.dim},bg=${gs3}}x ⇥"
  ];
  catalogue = writeText "prelude-shell-catalogue.bash" (
    import ./shell/catalogue.nix { inherit lib; } { inherit commandEntries; }
  );
  schemePalette = {
    inherit (palette)
      bg
      surface
      secondary
      fg
      muted
      dim
      border
      accent
      accent2
      success
      warning
      info
      error
      ;
    accent_border = palette.accentBorder;
    selection_fg = palette.selectionFg;
    shadow = resolvedShadow;
  };
  # Replace longer names first (`accent_border` and `accent2` before `accent`)
  # because the semantic markers intentionally share readable prefixes.
  schemeTokens = lib.sort (left: right: builtins.stringLength left > builtins.stringLength right) (
    lib.attrNames schemePalette
  );
  scheme = writeText "prelude.bash" (
    lib.replaceStrings (map (token: "%prelude_${token}") schemeTokens) (map (
      token: schemePalette.${token}
    ) schemeTokens) (builtins.readFile ./shell/scheme.bash)
  );

  runtime = runCommand "prelude-shell-runtime" { } ''
    install -d "$out" "$out/contrib/scheme"
    install -m 0444 ${./shell/init.bash} "$out/init.bash"
    install -m 0444 ${./shell/bash-init.bash} "$out/bash-init.bash"
    install -m 0444 ${./shell/status.bash} "$out/status.bash"
    install -m 0444 ${./shell/status-cap.bash} "$out/status-cap.bash"
    install -m 0444 ${./shell/completion.bash} "$out/completion.bash"
    install -m 0444 ${scheme} "$out/contrib/scheme/prelude.bash"
    install -m 0444 ${catalogue} "$out/catalogue.bash"
  '';

  init = writeText "prelude-init.bash" ''
    # Generated by Prelude. Source this file; do not execute it in a subshell.
    _PRELUDE_SHELL_RUNTIME=${lib.escapeShellArg runtime}
    _PRELUDE_BASH_COMPLETION=${lib.escapeShellArg "${bash-completion}/etc/profile.d/bash_completion.sh"}
    _PRELUDE_BLESH=${lib.escapeShellArg "${blesh}/share/blesh/ble.sh"}
    _PRELUDE_STARSHIP=${lib.escapeShellArg (lib.getExe starship)}
    _PRELUDE_STARSHIP_STATUS_ENABLED=${if statusEnabled then "1" else "0"}
    _PRELUDE_WINDOW_BACKGROUND_SET=${if windowBackgroundSet then "1" else "0"}
    _PRELUDE_PROMPT_PROJECT=${lib.escapeShellArg projectName}
    _PRELUDE_PROMPT_NAVIGATION=${lib.escapeShellArg navigationText}
    _PRELUDE_PROMPT_NAVIGATION_RENDERED=${lib.escapeShellArg navigationRendered}
    _PRELUDE_PROMPT_STATUS_HINT=${lib.escapeShellArg hintText}
    _PRELUDE_PROMPT_STATUS_HINT_RENDERED=${lib.escapeShellArg hintRendered}
    _PRELUDE_MOTD=${lib.escapeShellArg (if motdCommand == null then "" else motdCommand)}
    _PRELUDE_PROMPT_STATUS=${
      lib.escapeShellArg (if promptStatusCommand == null then "" else promptStatusCommand)
    }
    _PRELUDE_PROMPT_STATUS_CONFIG=${
      lib.escapeShellArg (if promptStatusConfig == null then "" else promptStatusConfig)
    }
    _PRELUDE_DARWIN=${if stdenv.isDarwin then "1" else ""}

    # shellcheck source=/dev/null
    . ${lib.escapeShellArg "${runtime}/init.bash"}

    unset _PRELUDE_SHELL_RUNTIME _PRELUDE_BASH_COMPLETION _PRELUDE_BLESH
    unset _PRELUDE_STARSHIP _PRELUDE_STARSHIP_STATUS_ENABLED _PRELUDE_PROMPT_PROJECT
    unset _PRELUDE_WINDOW_BACKGROUND_SET
    unset _PRELUDE_PROMPT_NAVIGATION _PRELUDE_PROMPT_NAVIGATION_RENDERED
    unset _PRELUDE_PROMPT_STATUS_HINT _PRELUDE_PROMPT_STATUS_HINT_RENDERED
    unset _PRELUDE_PROMPT_STATUS _PRELUDE_PROMPT_STATUS_CONFIG
    unset _PRELUDE_MOTD _PRELUDE_DARWIN
  '';
in
{
  inherit init runtime;
}
