# Build the canonical interactive-shell initialization used by packages.prelude.
#
# Runtime behavior lives in checked-in Bash modules under ./shell. Nix only
# serializes the evaluated command catalogue and injects immutable dependency
# paths, so changing shell behavior does not mean editing a large Nix string.
{
  lib,
  writeText,
  runCommand,
  starship,
  blesh,
  bash-completion,
  stdenv,
}:

{
  palette,
  commandEntries ? [ ],
  motdCommand ? null,
  statusEnabled ? false,
}:

let
  catalogue = writeText "prelude-shell-catalogue.bash" (
    import ./shell/catalogue.nix { inherit lib; } { inherit commandEntries; }
  );
  schemePalette = {
    inherit (palette)
      bg
      surface
      secondary
      fg
      muted
      dim
      border
      accent
      accent2
      success
      warning
      info
      error
      ;
    accent_border = palette.accentBorder;
    selection_fg = palette.selectionFg;
  };
  # Replace longer names first (`accent_border` and `accent2` before `accent`)
  # because the semantic markers intentionally share readable prefixes.
  schemeTokens = lib.sort (left: right: builtins.stringLength left > builtins.stringLength right) (
    lib.attrNames schemePalette
  );
  scheme = writeText "prelude.bash" (
    lib.replaceStrings (map (token: "%prelude_${token}") schemeTokens) (map (
      token: schemePalette.${token}
    ) schemeTokens) (builtins.readFile ./shell/scheme.bash)
  );

  runtime = runCommand "prelude-shell-runtime" { } ''
    install -d "$out" "$out/contrib/scheme"
    install -m 0444 ${./shell/init.bash} "$out/init.bash"
    install -m 0444 ${./shell/bash-init.bash} "$out/bash-init.bash"
    install -m 0444 ${./shell/status.bash} "$out/status.bash"
    install -m 0444 ${./shell/completion.bash} "$out/completion.bash"
    install -m 0444 ${scheme} "$out/contrib/scheme/prelude.bash"
    install -m 0444 ${catalogue} "$out/catalogue.bash"
  '';

  init = writeText "prelude-init.bash" ''
    # Generated by Prelude. Source this file; do not execute it in a subshell.
    _PRELUDE_SHELL_RUNTIME=${lib.escapeShellArg runtime}
    _PRELUDE_BASH_COMPLETION=${lib.escapeShellArg "${bash-completion}/etc/profile.d/bash_completion.sh"}
    _PRELUDE_BLESH=${lib.escapeShellArg "${blesh}/share/blesh/ble.sh"}
    _PRELUDE_STARSHIP=${lib.escapeShellArg (lib.getExe starship)}
    _PRELUDE_STARSHIP_STATUS_ENABLED=${if statusEnabled then "1" else "0"}
    _PRELUDE_MOTD=${lib.escapeShellArg (if motdCommand == null then "" else motdCommand)}
    _PRELUDE_DARWIN=${if stdenv.isDarwin then "1" else ""}

    # shellcheck source=/dev/null
    . ${lib.escapeShellArg "${runtime}/init.bash"}

    unset _PRELUDE_SHELL_RUNTIME _PRELUDE_BASH_COMPLETION _PRELUDE_BLESH
    unset _PRELUDE_STARSHIP _PRELUDE_STARSHIP_STATUS_ENABLED
    unset _PRELUDE_MOTD _PRELUDE_DARWIN
  '';
in
{
  inherit init runtime;
}
