# Generated by prelude setup.
#
# This file is intentionally separate from flake.nix so existing flakes are
# never overwritten. Wire it into your flake-parts flake:
#
#   inputs.prelude.url = "github:darkmatter/prelude";
#   # …
#   flake-parts.lib.mkFlake { inherit inputs; } {
#     imports = [
#       inputs.prelude.flakeModules.default
#       ./prelude.nix          # ← this file
#     ];
#     # …
#     perSystem = { config, ... }: {
#       devShells.default = pkgs.mkShell {
#         packages = [ config.packages.prelude ];
#         shellHook = "motd";
#       };
#     };
#   };
#
# Every supported option is listed below. Values you chose in the wizard are
# active; everything else is commented at its default so you can see and
# enable options without leaving this file. Defaults mirror
# src/prelude/defaults.nix. Full prose reference:
# docs/reference/options.md (regenerated by docs-sync).
#
{ ... }:
{
  prelude = {
    theme = "prelude";  # color theme for all components; default "prelude"

    # Per-token overrides on top of the theme (null keeps the theme token).
    # Values: null | hex string | ANSI-256 index.
    # palette.fg = null;
    # palette.muted = null;
    # palette.dim = null;
    # palette.border = null;
    # palette.accentBorder = null;
    # palette.accent = null;
    # palette.accent2 = null;
    # palette.success = null;
    # palette.warning = null;
    # palette.info = null;
    # palette.error = null;
    # palette.selectionFg = null;
    # palette.bg = null;
    # palette.surface = null;
    # palette.secondary = null;

    colorProfile = "auto";  # "auto" | "truecolor" | "ansi256"; default "auto"

    project = "acme";  # shown in the MOTD banner and menu header; default "acme"

    # Project commands keyed by public `x` name. The first colon infers the
    # menu group; the complete key stays callable (e.g. `x db:migrate`).
    # Defaults ship an ACME example catalogue (dev/test/build + database/ops);
    # defining any commands.* replaces that catalogue entirely.
    commands = {

      dev = {
        exec = "pnpm dev";  # defaults to the key suffix after the first colon
        description = "start the dev server with hot reload";
        # group inferred from key: develop  # first colon segment; builtins land in "prelude"
        # key = null;  # single-key accelerator (`x <key>`)
        # usage = "pnpm dev";  # usage form shown in menu details
        # details = null;  # extended description before arg entry
        # examples = [ "pnpm dev" ];  # worked example invocations
        # args = [ ];  # arg-entry mode: { token, description?, required?, boolean?, options? }
        # invocation = null;  # canonical shell text for duplicate detection; defaults to exec
        motd = 1;  # MOTD Getting Started sort order; null hides from MOTD
      };

      test = {
        exec = "pnpm test";  # defaults to the key suffix after the first colon
        description = "run the unit test suite";
        # group inferred from key: develop  # first colon segment; builtins land in "prelude"
        # key = null;  # single-key accelerator (`x <key>`)
        # usage = "pnpm test";  # usage form shown in menu details
        # details = null;  # extended description before arg entry
        # examples = [ "pnpm test" ];  # worked example invocations
        # args = [ ];  # arg-entry mode: { token, description?, required?, boolean?, options? }
        # invocation = null;  # canonical shell text for duplicate detection; defaults to exec
        motd = 2;  # MOTD Getting Started sort order; null hides from MOTD
      };

      build = {
        exec = "pnpm build";  # defaults to the key suffix after the first colon
        description = "compile an optimized production bundle";
        # group inferred from key: develop  # first colon segment; builtins land in "prelude"
        # key = null;  # single-key accelerator (`x <key>`)
        # usage = "pnpm build";  # usage form shown in menu details
        # details = null;  # extended description before arg entry
        # examples = [ "pnpm build" ];  # worked example invocations
        # args = [ ];  # arg-entry mode: { token, description?, required?, boolean?, options? }
        # invocation = null;  # canonical shell text for duplicate detection; defaults to exec
        motd = 3;  # MOTD Getting Started sort order; null hides from MOTD
      };
    };

    # Static devshell welcome banner.
    motd = {
      enable = true;


      title = {
        text = ./title.txt;  # multiline title file; null uses the project-name wordmark
        align = "center";  # left|center|right
        # style = "spine";  # wordmark when text is null: plain|spine|bracketed|label|inline|inverted
      };

      background = false;  # block fill: false/true, a color, or a relative/blend value
      windowBackground = true;  # full-width window fill
      border = false;  # rounded frame around the block
      clearScreen = true;  # clear the terminal before rendering
      align = "center";  # horizontal placement: left|center|right
      verticalAlign = "bottom";  # vertical placement after clear: top|center|bottom
      width = "full";  # content width or "full"
      maxWidth = 100;  # maximum content width
      # fullscreen = false;  # fill terminal width with no cap (width=full + maxWidth=null)

      # Outer spacing selected by the wizard (sides may be added after setup).
      margin = {
        x = 4;
        y = 2;
        minHeight = 40;
        # top = null;      # supersedes y
        # bottom = null;   # supersedes y; gated by minHeight
        # left = null;     # supersedes x
        # right = null;    # supersedes x
      };

      # Inner spacing selected by the wizard (sides may be added after setup).
      padding = {
        x = 4;
        y = 2;
        minHeight = 0;
        # top = null;
        # bottom = null;
        # left = null;
        # right = null;
      };

      # Hero: wizard-selected tagline and asynchronous status checks.
      header = {
        tagline = {
          text = "Fancy devshells for your nix flake";
          # subtitle = "";
          # layout = "stack";  # "stack" | "inline"
          # align = "left";  # "left" | "center"
        };
        # background = false;  # true = raised bar; null/false = transparent; color | { relative }
        # statusHint = {
        #   layout = "inline";  # "below" | "inline"
        #   links = [ ];  # terminal hyperlinks after the reload hint: { label, url }
        # };
        status = {

          flake = {
            order = 10;
            label = "flake";
            check = "nix flake check";
            async = true;  # refresh in the background; shell entry stays fast
            # ok = "ok";
            # fail = "fail";
            # failLevel = "error";  # "error" | "warning"
            # output = "";  # "" | "light" | "diagnostic"
          };


          # devServer = { label = "dev server"; check = "curl -fsS \"\${APP_HOST:-http://127.0.0.1:3000}/health\""; async = true; };

        };
      };

      # Styled text under the header; empty text hides it.
      description = {
        text = "You are now in the acme dev environment, powered by Nix Flakes. All required dependencies, project scripts, and documentation are available in this environment.";
        # foreground = null;  # null uses the theme role color
        # background = null;  # null/false | true | color | { relative }
        # bold = false;
        # italic = false;
        # faint = false;
      };

      # links = [ ];  # terminal hyperlinks under the description: { label, url }
      # env = [  # info chips; each sets exactly one of value (static) or probe (command)
      #   { label = "node"; value = "22"; }
      #   { label = "pnpm"; value = "9"; }
      #   { label = "postgres"; value = "16"; }
      #   # { label = "nix"; probe = "nix --version | awk '{print $NF}'"; }
      # ];
      # recipes = {  # multi-step workflows keyed by name
      #   first-run = {
      #     order = 100;
      #     title = "spin up a clean local stack";
      #     steps = [
      #       { comment = "start services, migrate, then run the app"; }
      #       { command = "x database:up"; }
      #       { command = "x database:migrate"; }
      #       { command = "dev"; }
      #     ];
      #   };
      # };

      # Labels for the commands + examples region.
      # gettingStarted = {
      #   heading = "Getting Started";
      #   commandsLabel = "commands";
      #   examplesLabel = "examples";
      #   commandNote = "prefix with `x` if a command is shadowed";  # "" hides it
      # };
    };

    # Interactive command picker (bubbletea TUI).
    menu = {
      enable = true;
      # placeholder = "type to filter commands…";  # filter input hint
      # height = 20;  # filter list height in rows
      # execute = true;  # false prints the selected command instead of running it
      # width = "full";  # content width or "full"
      # maxWidth = 80;
    };

    # Themed starship config (`packages.prompt` = starship.toml).
    prompt = {
      enable = true;
      # settings = { };  # merged over themed defaults; see https://starship.rs/config/
      #   # add_newline = true;
      #   # format = "$directory$git_branch$character";
      # configFile = null;  # use this starship.toml verbatim instead of generating one
    };

    # Markdown pages in the navigable docs viewer. Each file becomes one
    # CONTENTS sidebar entry; digits 1–9 jump between pages. The first
    # level-one heading labels the entry.
    # docs.pages = [
    #   { text = ./docs/getting-started.md; }
    #   # Or split one file into H2 leaves (bind the flake's lib):
    #   # (inputs.prelude.lib.mdSplit ./README.md)
    # ];
    docs.pages = [ ];

    # Preferred command-group order. Groups omitted follow alphabetically;
    # the built-in "prelude" group (menu/docs) stays first.
    # sort.groups = [ "develop" "database" "ops" ];
  };
}
