package main

import (
	"errors"
	"prelude/shared"
	"strings"
	"testing"

	"charm.land/lipgloss/v2"
	"github.com/charmbracelet/x/ansi"
)

type fakeRuntime struct {
	probes map[string]string
	failed map[string]bool
	git    GitInfo
	hasGit bool
}

func (f fakeRuntime) Probe(command string) (string, error) {
	if f.failed[command] {
		return "", errors.New("probe failed")
	}
	return f.probes[command], nil
}

func (f fakeRuntime) Git() (GitInfo, bool) {
	return f.git, f.hasGit
}

func testMOTDConfig() Config {
	return Config{
		Project: "prelude",
		Palette: shared.Palette{
			Fg:           "#d5e2d7",
			Muted:        "#7d8a81",
			Dim:          "#526057",
			Border:       "#344039",
			AccentBorder: "#2f6b4f",
			Accent:       "#3ddc84",
			Accent2:      "#d7a84b",
			Error:        "#ff6b6b",
			Bg:           "#0c110e",
			Surface:      "#131715",
			Secondary:    "#202622",
		},
		Background:       "#0c110e",
		WindowBackground: "#0c110e",
		Margin:           Spacing{Top: 1, Bottom: 1},
		Align:            "center",
		Padding:          Spacing{},
		Header: Header{
			TitleStyle:         "spine",
			Tagline:            "devshell UI, generated by Nix",
			StatusLabel:        "nix develop",
			StatusLabelCompact: "flake",
			StatusText:         "ready",
		},
		Description: StyledText{Text: "Generated without a shell rendering pipeline.", Foreground: "#d5e2d7", Background: "#0c110e"},
		Env: []EnvItem{
			{Label: "go", Probe: "go version"},
			{Label: "nix", Value: "2.34.7"},
			{Label: "missing", Probe: "missing"},
		},
		Commands: []Command{
			{Command: "menu", Description: "browse project commands"},
			{Command: "nix flake check", Description: "verify the flake"},
		},
		Recipes: []Recipe{{
			Title: "release",
			Steps: []RecipeStep{
				{Comment: "verify first"},
				{Command: "nix flake check"},
				{Command: "git push"},
			},
		}},
		Git: true,
		GettingStarted: GettingStarted{
			Heading:       "Getting Started",
			CommandsLabel: "Commands",
			ExamplesLabel: "Examples",
		},
		Shortcuts: []Shortcut{
			{Command: "help", Alias: "?"},
			{Command: "menu", Alias: "m"},
		},
		Width:    50,
		MaxWidth: 96,
	}
}

func TestRenderIncludesConfiguredSectionsAndRuntimeValues(t *testing.T) {
	cfg := testMOTDConfig()
	runtime := fakeRuntime{
		probes: map[string]string{"go version": "go1.25.0\nignored"},
		failed: map[string]bool{"missing": true},
		git:    GitInfo{Branch: "main", Ahead: 2, Dirty: 3},
		hasGit: true,
	}

	plain := ansi.Strip(render(cfg, 80, runtime))
	for _, want := range []string{
		"▌",
		"prelude",
		"ready",
		"devshell UI, generated by Nix",
		"Generated without a shell rendering pipeline.",
		"go go1.25.0",
		"nix 2.34.7",
		"git main ↑2 ●3",
		"Getting Started",
		"Commands",
		"$ menu",
		"browse project commands",
		"Examples",
		"release",
		"# verify first",
		"nix flake check",
		"git push",
		"help (?)",
		"menu (m)",
	} {
		if !strings.Contains(plain, want) {
			t.Fatalf("rendered MOTD does not contain %q:\n%s", want, plain)
		}
	}
	if strings.Contains(plain, "missing") {
		t.Fatalf("failed probe must be omitted:\n%s", plain)
	}
	// Numbered recipe steps and old footer are gone.
	if strings.Contains(plain, "1  $") || strings.Contains(plain, "next steps") {
		t.Fatalf("old layout leaked into output:\n%s", plain)
	}
}

func TestHeaderTitleVariants(t *testing.T) {
	variants := []struct {
		style string
		want  string
	}{
		{"spine", "▌"},
		{"plain", "prelude"},
		{"bracketed", "[ prelude ]"},
		{"label", "devshell / prelude"},
	}
	for _, tt := range variants {
		t.Run(tt.style, func(t *testing.T) {
			cfg := testMOTDConfig()
			cfg.Header.TitleStyle = tt.style
			cfg.Commands = nil
			cfg.Recipes = nil
			cfg.Shortcuts = nil
			cfg.Env = nil
			cfg.Git = false
			cfg.Description.Text = ""
			plain := ansi.Strip(render(cfg, 80, fakeRuntime{}))
			if !strings.Contains(plain, tt.want) {
				t.Fatalf("titleStyle %q missing %q:\n%s", tt.style, tt.want, plain)
			}
		})
	}
}

func TestRenderPaintsEveryWindowBackgroundRow(t *testing.T) {
	cfg := testMOTDConfig()
	rendered := strings.TrimSuffix(render(cfg, 80, fakeRuntime{}), "\n")

	for index, line := range strings.Split(rendered, "\n") {
		if got := lipgloss.Width(line); got != 80 {
			t.Fatalf("line %d width = %d, want 80", index, got)
		}
		if line == ansi.Strip(line) {
			t.Fatalf("line %d has no styling, so its background is transparent", index)
		}
	}
}

func TestResolveCardWidthHonorsFullFixedMaximumAndMinimum(t *testing.T) {
	tests := []struct {
		name      string
		width     int
		maxWidth  int
		terminal  int
		wantWidth int
	}{
		{name: "full width capped", width: 0, maxWidth: 96, terminal: 120, wantWidth: 96},
		{name: "full width uncapped", width: 0, terminal: 72, wantWidth: 72},
		{name: "fixed width capped", width: 100, maxWidth: 80, terminal: 120, wantWidth: 80},
		{name: "minimum", width: 4, terminal: 120, wantWidth: 10},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := resolveCardWidth(tt.width, tt.maxWidth, tt.terminal); got != tt.wantWidth {
				t.Fatalf("card width = %d, want %d", got, tt.wantWidth)
			}
		})
	}
}

func TestHeaderStaysEdgeToEdgeWithPadding(t *testing.T) {
	cfg := testMOTDConfig()
	cfg.ClearScreen = false
	cfg.Margin = Spacing{}
	cfg.WindowBackground = ""
	cfg.Padding = Spacing{Left: 2, Right: 2}
	cfg.Width = 40
	cfg.Shortcuts = nil

	plain := ansi.Strip(render(cfg, 40, fakeRuntime{}))
	lines := strings.Split(strings.TrimSuffix(plain, "\n"), "\n")
	if len(lines) < 2 {
		t.Fatalf("expected multiple lines, got %d:\n%s", len(lines), plain)
	}

	// Header wordmark row is edge-to-edge (no content left pad).
	var headerLine string
	for _, line := range lines {
		if strings.Contains(line, "prelude") && strings.Contains(line, "ready") {
			headerLine = line
			break
		}
	}
	if headerLine == "" {
		t.Fatalf("header row not found:\n%s", plain)
	}
	if strings.HasPrefix(headerLine, "  ▌") == false && strings.HasPrefix(strings.TrimLeft(headerLine, " "), "▌") {
		// spine title may have leading spaces from the title itself ("  ▌ ")
	}
	if got := ansi.StringWidth(headerLine); got != 40 {
		t.Fatalf("header width = %d, want 40 (edge-to-edge)", got)
	}
}

func TestCommandLeadersBridgeDescription(t *testing.T) {
	cfg := testMOTDConfig()
	cfg.ClearScreen = false
	cfg.Margin = Spacing{}
	cfg.Recipes = nil
	cfg.Shortcuts = nil
	cfg.Env = nil
	cfg.Git = false
	cfg.Description.Text = ""
	cfg.Header.Tagline = ""
	cfg.Header.StatusText = ""
	cfg.Header.StatusLabel = ""

	plain := ansi.Strip(render(cfg, 80, fakeRuntime{}))
	if !strings.Contains(plain, "·") {
		t.Fatalf("expected dotted leaders in command rows:\n%s", plain)
	}
	if !strings.Contains(plain, "$ menu") {
		t.Fatalf("expected command prefix:\n%s", plain)
	}
}
