package menu

import (
	"fmt"
	"strings"

	"prelude/pkg/shared"
)

// Config mirrors the JSON payload generated by src/prelude/menu.nix (and by the
// TypeScript API in ts/, which authors the same boundary for libprelude).
type Config struct {
	Project      string         `json:"project"`
	Placeholder  string         `json:"placeholder"`
	Height       int            `json:"height"`
	MaxWidth     int            `json:"maxWidth"` // 0 = unbounded
	Execute      bool           `json:"execute"`
	ColorProfile string         `json:"colorProfile"`
	Palette      shared.Palette `json:"palette"`
	Groups       []Group        `json:"groups"`
	MOTDCommands []CommandHint  `json:"motdCommands"`
	Just         JustConfig     `json:"just"`
	Scripts      ScriptsConfig  `json:"scripts"`
	// Dispatcher is the public command that opens this picker and runs its
	// keys. Empty means the devshell's `x`; a TypeScript app names itself.
	Dispatcher string `json:"dispatcher,omitempty"`

	importWarnings []string // imports that failed, said under `x --list`
}

// JustConfig controls the optional runtime import from a Justfile. A nil
// Justfile uses just's normal discovery from the current working directory.
type JustConfig struct {
	Enable   bool    `json:"enable"`
	Justfile *string `json:"justfile"`
	Group    string  `json:"group"`
}

// ScriptsConfig controls the optional runtime import of package.json scripts.
// A nil PackageJSON uses the nearest package.json at or above the working
// directory. A relative one resolves from the project root, the nearest
// directory holding flake.nix, else from the working directory.
type ScriptsConfig struct {
	Enable      bool    `json:"enable"`
	PackageJSON *string `json:"packageJson"`
	Group       string  `json:"group"`
}

// dispatcher is the command that runs this catalogue's keys.
func (c *Config) dispatcher() string {
	if c.Dispatcher == "" {
		return "x"
	}
	return c.Dispatcher
}

// CommandHint is the reduced command projection used by compact catalogue
// surfaces. Menu itself continues to render the richer Task values.
type CommandHint struct {
	Name        string `json:"name"`
	Command     string `json:"command"`
	Description string `json:"description"`
}

type Group struct {
	Title string `json:"title"`
	Tasks []Task `json:"tasks"`
}

type Task struct {
	Name        string   `json:"name"`
	Label       string   `json:"label"`
	Run         string   `json:"run"`
	Command     string   `json:"command"` // user-runnable shell form (possibly "x <key>")
	Description string   `json:"description"`
	Key         string   `json:"key"`   // "" = none
	Usage       string   `json:"usage"` // "" = none
	Details     string   `json:"details"`
	Examples    []string `json:"examples"`
	Args        []Arg    `json:"args"`
	// Children are the task's subcommands, nested to any depth. They never
	// appear in the root list: a task with children is one row that opens a
	// subcommand picker over them, and `x` reaches each one by its label, one
	// word per level (`x db seed users`). Leaves carry no children.
	Children []Task `json:"children,omitempty"`
	// Source is where the task came from; "" means declared, in Nix or by a
	// host. Imports set it.
	Source string `json:"source,omitempty"`
	// Dir is the directory Run runs in ("" = the caller's), and PathPrefix
	// the directories put ahead of PATH for it, nearest first.
	Dir        string   `json:"dir,omitempty"`
	PathPrefix []string `json:"pathPrefix,omitempty"`

	group    string        // owning group title
	haystack string        // precomputed lowercase filter target
	justPath []string      // public argv route for an explicitly grouped module recipe
	hides    []hiddenEntry // imports this task hid by claiming their key first
	// justModule marks a just module container built by the just import. Its
	// Run is just's dispatch form for the module, so words the menu does not
	// know pass through for just to resolve instead of being rejected.
	justModule bool
}

func (t Task) displayName() string {
	if t.Label != "" {
		return t.Label
	}
	return t.Name
}

// isContainer reports whether choosing t opens its subcommand picker instead
// of running it: a task with children and nothing of its own to run, or a just
// module. A task with children and its own Run is a runnable parent, which
// runs like a leaf and opens its children only on request.
func (t Task) isContainer() bool {
	return len(t.Children) > 0 && (t.Run == "" || t.justModule)
}

// subcommandsDescription describes an imported container by how many
// subcommands it opens, as the Nix catalogue describes one declared without
// a description.
func subcommandsDescription(count int) string {
	if count == 1 {
		return "1 subcommand"
	}
	return fmt.Sprintf("%d subcommands", count)
}

type Arg struct {
	Token       string   `json:"token"`
	Description string   `json:"description"`
	Required    bool     `json:"required"`
	Boolean     bool     `json:"boolean"`
	Options     []string `json:"options"`
	Default     *string  `json:"default"`
}

func loadConfig(path string) (*Config, error) {
	if path == "" {
		return nil, fmt.Errorf("no config: pass --config or set PRELUDE_MENU_CONFIG")
	}
	cfg, err := shared.LoadJSON[Config](path)
	if err != nil {
		return nil, err
	}
	cfg.applyDefaults()
	return cfg, nil
}

func (c *Config) applyDefaults() {
	if c.Height <= 0 {
		c.Height = 12
	}
}

// taskHaystack is the lowercase filter target for one task alone.
func taskHaystack(t Task) string {
	return strings.ToLower(
		t.Name + " " + t.displayName() + " " + t.Usage + " " + t.Description + " " + t.group,
	)
}

// searchable returns a copy of tasks with filter haystacks attached at every
// depth. A task's haystack folds in all of its descendants', so a query for a
// nested subcommand still surfaces the row that leads to it.
func searchable(tasks []Task) []Task {
	if len(tasks) == 0 {
		return nil
	}
	out := make([]Task, len(tasks))
	for index, task := range tasks {
		task.Children = searchable(task.Children)
		task.haystack = taskHaystack(task)
		for _, child := range task.Children {
			task.haystack += " " + child.haystack
		}
		out[index] = task
	}
	return out
}

// flatten returns every top-level task in group order with search metadata
// attached. Subcommands stay out of the root list behind their parent row.
func (c *Config) flatten() []Task {
	var flat []Task
	for _, g := range c.Groups {
		tasks := make([]Task, len(g.Tasks))
		for index, task := range g.Tasks {
			task.group = g.Title
			tasks[index] = task
		}
		flat = append(flat, searchable(tasks)...)
	}
	return flat
}
