package menu

import (
	"fmt"
	"strings"

	"prelude/pkg/shared"
)

// Config mirrors the JSON payload generated by src/prelude/menu.nix (and by the
// TypeScript API in ts/, which authors the same boundary for libprelude).
type Config struct {
	Project      string         `json:"project"`
	Placeholder  string         `json:"placeholder"`
	Height       int            `json:"height"`
	MaxWidth     int            `json:"maxWidth"` // 0 = unbounded
	Execute      bool           `json:"execute"`
	ColorProfile string         `json:"colorProfile"`
	Palette      shared.Palette `json:"palette"`
	Groups       []Group        `json:"groups"`
	MOTDCommands []CommandHint  `json:"motdCommands"`
	Just         JustConfig     `json:"just"`
	// Dispatcher is the public command that opens this picker and runs its
	// keys. Empty means the devshell's `x`; a TypeScript app names itself.
	Dispatcher string `json:"dispatcher,omitempty"`

	justImportWarning string
}

// JustConfig controls the optional runtime import from a Justfile. A nil
// Justfile uses just's normal discovery from the current working directory.
type JustConfig struct {
	Enable   bool    `json:"enable"`
	Justfile *string `json:"justfile"`
	Group    string  `json:"group"`
}

// CommandHint is the reduced command projection used by compact catalogue
// surfaces. Menu itself continues to render the richer Task values.
type CommandHint struct {
	Name        string `json:"name"`
	Command     string `json:"command"`
	Description string `json:"description"`
}

type Group struct {
	Title string `json:"title"`
	Tasks []Task `json:"tasks"`
}

type Task struct {
	Name        string   `json:"name"`
	Label       string   `json:"label"`
	Run         string   `json:"run"`
	Command     string   `json:"command"` // user-runnable shell form (possibly "x <key>")
	Description string   `json:"description"`
	Key         string   `json:"key"`   // "" = none
	Usage       string   `json:"usage"` // "" = none
	Details     string   `json:"details"`
	Examples    []string `json:"examples"`
	Args        []Arg    `json:"args"`
	// Children are the task's subcommands. A just module imports as one menu
	// row and its recipes stay behind it: selecting the row (or `x <name>`)
	// opens a subcommand picker. Children never appear in the root list and
	// keep their complete key (`module::recipe`) for Just execution.
	Children []Task `json:"children"`

	group    string   // owning group title
	haystack string   // precomputed lowercase filter target
	justPath []string // public argv route for an imported module recipe
}

func (t Task) displayName() string {
	if t.Label != "" {
		return t.Label
	}
	return t.Name
}

type Arg struct {
	Token       string   `json:"token"`
	Description string   `json:"description"`
	Required    bool     `json:"required"`
	Boolean     bool     `json:"boolean"`
	Options     []string `json:"options"`
	Default     *string  `json:"default"`
}

func loadConfig(path string) (*Config, error) {
	if path == "" {
		return nil, fmt.Errorf("no config: pass --config or set PRELUDE_MENU_CONFIG")
	}
	cfg, err := shared.LoadJSON[Config](path)
	if err != nil {
		return nil, err
	}
	cfg.applyDefaults()
	return cfg, nil
}

func (c *Config) applyDefaults() {
	if c.Height <= 0 {
		c.Height = 12
	}
}

// taskHaystack is the lowercase filter target for one task. flatten computes
// it for top-level tasks; the just import precomputes it for subcommand
// children, which enter filtering through the submenu's flat list.
func taskHaystack(t Task) string {
	return strings.ToLower(
		t.Name + " " + t.displayName() + " " + t.Usage + " " + t.Description + " " + t.group,
	)
}

// flatten returns every top-level task in group order with search metadata
// attached. Subcommand children stay out of the root list, but their names
// and descriptions are folded into the parent's haystack so a query like
// "desktop" still surfaces the module row that owns them.
func (c *Config) flatten() []Task {
	var flat []Task
	for _, g := range c.Groups {
		for _, t := range g.Tasks {
			t.group = g.Title
			t.haystack = taskHaystack(t)
			for index := range t.Children {
				child := t.Children[index]
				if child.haystack == "" {
					child.haystack = taskHaystack(child)
					t.Children[index] = child
				}
				t.haystack += " " + child.haystack
			}
			flat = append(flat, t)
		}
	}
	return flat
}
