package menu

import (
	"fmt"
	"strings"

	"prelude/pkg/shared"
)

// Config mirrors the JSON payload generated by src/prelude/menu.nix.
type Config struct {
	Project      string         `json:"project"`
	Placeholder  string         `json:"placeholder"`
	Height       int            `json:"height"`
	MaxWidth     int            `json:"maxWidth"` // 0 = unbounded
	Execute      bool           `json:"execute"`
	ColorProfile string         `json:"colorProfile"`
	Palette      shared.Palette `json:"palette"`
	Groups       []Group        `json:"groups"`
}

type Group struct {
	Title string `json:"title"`
	Tasks []Task `json:"tasks"`
}

type Task struct {
	Name        string   `json:"name"`
	Run         string   `json:"run"`
	Description string   `json:"description"`
	Key         string   `json:"key"`   // "" = none
	Usage       string   `json:"usage"` // "" = none
	Details     string   `json:"details"`
	Examples    []string `json:"examples"`
	Args        []Arg    `json:"args"`

	group    string // owning group title
	haystack string // precomputed lowercase filter target
}

type Arg struct {
	Token       string   `json:"token"`
	Description string   `json:"description"`
	Required    bool     `json:"required"`
	Boolean     bool     `json:"boolean"`
	Options     []string `json:"options"`
}

func loadConfig(path string) (*Config, error) {
	if path == "" {
		return nil, fmt.Errorf("no config: pass --config or set PRELUDE_MENU_CONFIG")
	}
	cfg, err := shared.LoadJSON[Config](path)
	if err != nil {
		return nil, err
	}
	if cfg.Height <= 0 {
		cfg.Height = 12
	}
	return cfg, nil
}

// flatten returns every task in group order with search metadata attached.
func (c *Config) flatten() []Task {
	var flat []Task
	for _, g := range c.Groups {
		for _, t := range g.Tasks {
			t.group = g.Title
			t.haystack = strings.ToLower(
				t.Name + " " + t.Usage + " " + t.Description + " " + t.group,
			)
			flat = append(flat, t)
		}
	}
	return flat
}
